### ISSUE TITLE
Migrate to requests

### ISSUE THREAD

**Issue by zyegfryed** [slipstream/SlipStreamClient#32] opened 2014-01-29 11:48 UTC
Right now SlipStreamClient relies on `httplib2` which is old and doesn't provide modularity and extensibility.
[`Requests`](http://python-requests.org) library is a modern way of dealing with HTTP and easier to use/modify.

**Comment by konstan** [comment] 2015-04-24 13:14
Duplicate of #14. Closing.

**Closed by konstan** 2015-04-24 13:14 UTC
Labels: duplicate, enhancement
